### PR TITLE
Bump Elixir version to ~> 1.10 and use Application.compile_env/3 instead of Application.get_env/3

### PR DESCRIPTION
**Pull request by rbino**
Avoid compiler warning and remove disabled Credo check

### CODE REVIEW

**Comment by sobolevn** [comment]
Hi! Thanks for the fix! Can you please also take a look at the Elixir installation failure?

**Comment by rbino** [comment]
I made a separate PR for that https://github.com/wemake-services/recase/pull/163

**Comment by sobolevn** [comment]
Retriggering! Thanks

**Comment by rbino** [comment]
@sobolevn I have to think about how handle this for Elixir < 1.10 (where `Application.compile_env` was introduced), I'm going to draft the PR until it's ready to go

**Comment by sobolevn** [comment]
Yes, good idea!

**Comment by rbino** [comment]
@sobolevn I bumped the Elixir version to 1.10 and fixed the CI, this should be good to go

**Review by sobolevn — APPROVED** [review]
Thanks a lot!

**Pull request merged**
